<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Platforms>x64</Platforms>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <OutputPath>..\out\$(Configuration)\</OutputPath>
    </PropertyGroup>

    <PropertyGroup>
        <Authors>Zachary Kerr</Authors>
        <Company>FoodUmbra</Company>
        <Version>0.1.0</Version>
        <Description>Food browser for Umbra</Description>
        <PackageProjectUrl>https://github.com/una-xiv/umbra</PackageProjectUrl>
        <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <PropertyGroup>
        <DalamudLibPath Condition="'$(DalamudLibPath)' == ''">/run/media/system/4tb_hd/Game-Resources/Final Fantasy 14/XIVLauncher/dalamud/Hooks/dev/</DalamudLibPath>
        <UmbraLibPath Condition="'$(UmbraLibPath)' == ''">/run/media/system/4tb_hd/Game-Resources/Final Fantasy 14/XIVLauncher/installedPlugins/Umbra/3.1.18.0/</UmbraLibPath>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="Umbra">
            <HintPath>..\lib\Umbra.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Umbra.Common">
            <HintPath>..\lib\Umbra.Common.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Umbra.Game">
            <HintPath>..\lib\Umbra.Game.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Una.Drawing">
            <HintPath>..\lib\Una.Drawing.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Dalamud">
            <HintPath>..\lib\Dalamud.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="FFXIVClientStructs">
            <HintPath>..\lib\FFXIVClientStructs.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Lumina">
            <HintPath>..\lib\Lumina.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Lumina.Excel">
            <HintPath>..\lib\Lumina.Excel.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>

</Project>
