name: Build Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "10.0.x"

      - name: Get Umbra dependencies
        run: |
          git clone --depth 1 https://github.com/una-xiv/umbra-dist.git umbra-dist

      - name: Get Dalamud
        run: |
          mkdir -p ~/.xlcore/dalamud/Hooks/dev
          curl -L https://goatcorp.github.io/dalamud-distrib/latest.zip -o dalamud.zip
          unzip -q dalamud.zip -d ~/.xlcore/dalamud/Hooks/dev
          rm dalamud.zip
      
      - name: Build
        run: |
          dotnet build FoodUmbra.csproj \
            --configuration Release
      
      - name: Check build output
        run: |
          find out -type f -maxdepth 3 -print
          test -f out/Release/FoodUmbra.dll

      - name: Upload build artifact
        uses: actions/upload-artifact@v1
        with:
          name: FoodUmbra
          path: out/Release/FoodUmbra.dll
      
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: out/Release/FoodUmbra.dll
